Bugfix: Don't expect LD_LIBRARY_PATH to be always a string.
In some environments (e.g. AWS_ECS_EC2) process.env.LD_LIBRARY_PATH can be undefined yielding the following error:

```
  if (process.env.LD_LIBRARY_PATH.startsWith('/tmp/aws/lib') !== true) {
                                  ^

TypeError: Cannot read property 'startsWith' of undefined
```

This commit fixes the issue by ensuring that LD_LIBRARY_PATH set.